spring:
  application:
    name: file-service
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:h2:file:./data/file-service;DB_CLOSE_ON_EXIT=false
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8085
# AWS S3 configuration (replace placeholders)
aws:
  s3:
    bucketName: job-portal-files-162803876420
    region: eu-north-1
    accessKey: ${AWS_ACCESS_KEY_ID}
    secretKey: ${AWS_SECRET_ACCESS_KEY}
    presignUploadTtl: PT15M
    presignDownloadTtl: PT5M
    maxResumeSize: 5242880



# local storage fallback (optional)
file:
  temp-dir: ./upload-dir
  public-base-url: http://localhost:8086   # PUBLIC url (gateway) used to build local download links


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
